# This is a basic workflow to help you get started with Actions

name: main

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout # 步骤的名称
      uses: actions/checkout@v1 #软件市场的名称
      with: # 参数
          submodules: true
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.2
      with:
          hugo-version: '0.64.1'
          extended: true
    - name: Build Blog
      run: hugo -D
    
    # 使用大佬提供的代码 - https://github.com/manyuanrong/setup-ossutil
    - uses: actions/checkout@master
    - uses: manyuanrong/setup-ossutil@v2.0
      with:
        # endpoint 可以去oss控制台上查看
        endpoint: "oss-cn-beijing.aliyuncs.com"
        # 使用我们之前配置在secrets里面的accesskeys来配置ossutil
        access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
    - name: Deply To OSS
      run: ossutil cp ./ oss://billie-s-blog/ -rf

